import { Link } from 'react-router-dom'

const pages = {
  about: ['About Shopwise', 'Software built around the daily work of an independent shop.', [['What Shopwise does', 'Owners manage products, inventory, shopkeepers, sales, payments, and reports. Shopkeepers receive a focused POS without owner-only controls.'], ['How it is built', 'Shopwise uses React, a Node.js API, Supabase, Stripe Elements, and Resend.'], ['Honest payment states', 'Cash completes immediately. M-Pesa remains pending. Card payments complete only after a verified backend webhook.']]],
  privacy: ['Privacy information', 'Shopwise processes information required to provide MiniPOS functionality.', [['Information processed', 'Account details, shop and product records, inventory movements, staff memberships, sales, payment status, returns, reports, request identifiers, and security logs.'], ['Service providers', 'Supabase provides authentication and data services, Railway hosts the API, Vercel can host the frontend, Stripe processes cards, and Resend delivers report emails.'], ['Payment information', 'Stripe Elements collects card details; Shopwise does not store them.'], ['Access and security', 'Backend authorization and database policies scope business records to the appropriate shop.']]],
  terms: ['Terms of use', 'Use Shopwise only for lawful shop-management activity.', [['Account responsibility', 'Protect credentials, limit staff access, and review activity recorded under your shop.'], ['Business records', 'Owners remain responsible for validating prices, inventory, transactions, reports, taxes, and regulatory obligations.'], ['Payments', 'Verify provider settlement before treating a pending payment as complete.'], ['Acceptable use', 'Do not impersonate others, collect credentials fraudulently, bypass controls, or conduct illegal transactions.']]],
  contact: ['Contact Shopwise', 'For technical problems, security concerns, or project questions, use the official source repository.', [['Project support', 'Open an issue without including passwords, tokens, payment secrets, card details, or sensitive shop data.'], ['Security reports', 'Do not post secrets publicly. Share only enough non-sensitive information to describe the affected area.']]],
}

export function InfoPage({ page }) { const [title, intro, sections] = pages[page]; return <div className="min-h-screen bg-white"><header className="mx-auto flex h-18 max-w-5xl items-center justify-between px-5"><Link to="/" className="flex items-center gap-2 font-extrabold"><span className="grid size-9 place-items-center rounded-lg bg-brand-600 text-white">S</span>Shopwise</Link><Link to="/login" className="text-sm font-bold text-brand-700">Sign in</Link></header><main className="mx-auto max-w-3xl px-5 py-16"><p className="text-xs font-extrabold uppercase tracking-widest text-brand-600">{page}</p><h1 className="mt-3 text-4xl font-extrabold">{title}</h1><p className="mt-5 text-lg leading-8 text-gray-600">{intro}</p><div className="mt-12 grid gap-9">{sections.map(([heading,text])=><section key={heading}><h2 className="text-xl font-bold">{heading}</h2><p className="mt-2 leading-7 text-gray-600">{text}</p></section>)}</div>{page==='contact'&&<a className="mt-10 inline-block font-bold text-brand-700 underline" href="https://github.com/jjibrah/ShopManagementSystem/issues" target="_blank" rel="noreferrer">Open GitHub issues</a>}</main><footer className="mx-auto flex max-w-5xl gap-5 border-t px-5 py-6 text-xs text-gray-500"><Link to="/about">About</Link><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/contact">Contact</Link></footer></div> }
