import { AppError } from '../../errors/AppError.js'

const publicIntegration = (row) => row ? ({ preference:row.preference,environment:row.environment,shortcodeType:row.shortcode_type,shortcode:row.shortcode,storeNumber:row.store_number,businessName:row.business_name,paymentInstructions:row.payment_instructions,status:row.status,credentialsConfigured:Boolean(row.consumer_key_encrypted&&row.consumer_secret_encrypted&&row.passkey_encrypted),lastVerifiedAt:row.last_verified_at,lastError:row.last_error }) : ({preference:'not_selected',status:'not_started',credentialsConfigured:false})
const publicAttempt = row => ({id:row.id,saleId:row.sale_id,status:row.status,amount:row.amount,phoneNumber:row.phone_number,providerReceiptNumber:row.provider_receipt_number,failureCode:row.failure_code,failureMessage:row.failure_message,requestedAt:row.requested_at,completedAt:row.completed_at})
export class MpesaService {
  constructor({repository,shopService,gateway,cipher,publicApiUrl,logger}){Object.assign(this,{repository,shopService,gateway,cipher,publicApiUrl,logger})}
  async context(auth, owner=false){const context=await this.shopService.getCurrentShopContext(auth);if(owner&&(context.membership.role!=='owner'||context.shop.owner_id!==auth.userId))throw AppError.forbidden('Only the shop owner can configure M-Pesa');return context}
  credentials(row){return{environment:row.environment,shortcodeType:row.shortcode_type,shortcode:row.shortcode,storeNumber:row.store_number,consumerKey:this.cipher.decrypt(row.consumer_key_encrypted),consumerSecret:this.cipher.decrypt(row.consumer_secret_encrypted),passkey:this.cipher.decrypt(row.passkey_encrypted)}}
  async availability(auth){const {shop}=await this.context(auth);const row=await this.repository.getIntegration(shop.id);const value=publicIntegration(row);return{...value,methods:{cash:true,manualMpesa:value.preference!=='not_using',stkMpesa:value.preference==='integrated'&&value.status==='active',card:true}}}
  async settings(auth){const {shop}=await this.context(auth,true);return publicIntegration(await this.repository.getIntegration(shop.id))}
  async save(auth,input){const {shop}=await this.context(auth,true),existing=await this.repository.getIntegration(shop.id);const integrated=input.preference==='integrated';const encrypted={};if(input.consumerKey)encrypted.consumer_key_encrypted=this.cipher.encrypt(input.consumerKey);if(input.consumerSecret)encrypted.consumer_secret_encrypted=this.cipher.encrypt(input.consumerSecret);if(input.passkey)encrypted.passkey_encrypted=this.cipher.encrypt(input.passkey);const hasCredentials=Boolean(encrypted.consumer_key_encrypted||existing?.consumer_key_encrypted)&&Boolean(encrypted.consumer_secret_encrypted||existing?.consumer_secret_encrypted)&&Boolean(encrypted.passkey_encrypted||existing?.passkey_encrypted);const status=input.preference==='manual'?'manual_enabled':input.preference==='not_using'?'disabled':integrated&&hasCredentials?'credentials_entered':'not_started';const row=await this.repository.saveIntegration(shop.id,{preference:input.preference,environment:input.environment,shortcode_type:input.shortcodeType,shortcode:input.shortcode,store_number:input.storeNumber,business_name:input.businessName,payment_instructions:input.paymentInstructions,status,last_error:null,...encrypted});return publicIntegration(row)}
  async verify(auth){const {shop}=await this.context(auth,true),row=await this.repository.getIntegration(shop.id);if(!row||row.preference!=='integrated')throw AppError.conflict('MPESA_NOT_CONFIGURED','Choose integrated M-Pesa and save credentials first');try{await this.gateway.verify(this.credentials(row));const updated=await this.repository.saveIntegration(shop.id,{status:'active',last_verified_at:new Date().toISOString(),last_error:null});return publicIntegration(updated)}catch(error){await this.repository.saveIntegration(shop.id,{status:'verification_failed',last_error:error.message});throw error}}
  async initiate(auth,input){const {shop}=await this.context(auth),integration=await this.repository.getIntegration(shop.id);if(!integration||integration.preference!=='integrated'||integration.status!=='active')throw AppError.conflict('MPESA_NOT_ACTIVE','Integrated M-Pesa is not active for this shop');const sale=await this.repository.paymentContext(shop.id,input.saleId,auth.token),payment=sale?.payments?.find(p=>p.method==='mpesa');if(!sale||!payment)throw AppError.notFound('PAYMENT_NOT_FOUND','Eligible M-Pesa sale was not found');if(payment.status==='completed')throw AppError.conflict('SALE_ALREADY_PAID','Sale has already been paid');const attempt=await this.repository.createAttempt({shop_id:shop.id,sale_id:sale.id,payment_id:payment.id,amount:payment.amount,phone_number:input.phoneNumber,idempotency_key:input.idempotencyKey});if(attempt.checkout_request_id)return publicAttempt(attempt);try{const response=await this.gateway.stkPush(this.credentials(integration),{amount:payment.amount,phoneNumber:input.phoneNumber,accountReference:sale.receipt_number,callbackUrl:`${this.publicApiUrl}/api/v1/webhooks/mpesa/daraja`});if(!response.CheckoutRequestID)throw new AppError(502,'MPESA_REQUEST_FAILED',response.ResponseDescription||'M-Pesa did not accept the request');return publicAttempt(await this.repository.markProcessing(attempt.id,response))}catch(error){await this.repository.markInitiationFailed(attempt.id,error);throw error}}
  async attempt(auth,id){const {shop}=await this.context(auth),row=await this.repository.getAttempt(shop.id,id);if(!row)throw AppError.notFound('PAYMENT_ATTEMPT_NOT_FOUND','Payment attempt was not found');return publicAttempt(row)}
  async manual(auth,input){await this.context(auth);return this.repository.confirmManual(input.paymentId,input.receiptNumber,auth.token)}
  async callback(body,requestId){const callback=body?.Body?.stkCallback;if(!callback?.CheckoutRequestID)return{received:true,ignored:true};const items=Object.fromEntries((callback.CallbackMetadata?.Item||[]).map(item=>[item.Name,item.Value]));const code=Number(callback.ResultCode),status=code===0?'completed':code===1032?'cancelled':code===1037?'timed_out':'failed';const result=await this.repository.processResult({p_checkout_request_id:callback.CheckoutRequestID,p_status:status,p_receipt_number:items.MpesaReceiptNumber?String(items.MpesaReceiptNumber):null,p_failure_code:String(callback.ResultCode),p_failure_message:callback.ResultDesc||null,p_raw_callback:body});this.logger.info('mpesa_callback_processed',{requestId,checkoutRequestId:callback.CheckoutRequestID,status});return{received:true,...result}}
}
