import { AppError } from '../../errors/AppError.js'
const publicExpense = (row) => ({ id: row.id, category: row.category, description: row.description, amount: row.amount, expenseDate: row.expense_date, paymentMethod: row.payment_method, reference: row.reference, notes: row.notes, recordedBy: row.recorded_by, createdAt: row.created_at, updatedAt: row.updated_at })
export class ExpenseService {
  constructor({ expenseRepository, shopService, logger }) { Object.assign(this, { expenseRepository, shopService, logger }) }
  async context(auth) { const c = await this.shopService.getCurrentShopContext(auth); if (c.membership.role !== 'owner' || c.shop.owner_id !== auth.userId) throw AppError.forbidden('Expenses are restricted to the shop owner'); return c }
  async list(auth, filters) { const c = await this.context(auth); const r = await this.expenseRepository.list(c.shop.id, filters, auth.token); return { items: r.rows.map(publicExpense), pagination: { page: filters.page, pageSize: filters.pageSize, total: r.count, totalPages: Math.ceil(r.count / filters.pageSize) } } }
  async create(auth, input, requestId) { const c = await this.context(auth); const row = await this.expenseRepository.create(c.shop.id, auth.userId, input, auth.token); this.logger.info('expense_created', { requestId, shopId: c.shop.id, expenseId: row.id }); return publicExpense(row) }
  async update(auth, id, input, requestId) { const c = await this.context(auth); const row = await this.expenseRepository.update(c.shop.id, id, input, auth.token); if (!row) throw AppError.notFound('EXPENSE_NOT_FOUND', 'Expense was not found'); this.logger.info('expense_updated', { requestId, shopId: c.shop.id, expenseId: id }); return publicExpense(row) }
  async archive(auth, id, requestId) { const c = await this.context(auth); const row = await this.expenseRepository.archive(c.shop.id, id, auth.token); if (!row) throw AppError.notFound('EXPENSE_NOT_FOUND', 'Expense was not found'); this.logger.info('expense_archived', { requestId, shopId: c.shop.id, expenseId: id }); return publicExpense(row) }
  async summary(auth, filters) { const c = await this.context(auth); const now = new Date(); const start = filters.dateFrom || new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)).toISOString().slice(0, 10); const end = filters.dateTo || new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 0)).toISOString().slice(0, 10); const rows = await this.expenseRepository.summary(c.shop.id, start, end, auth.token); const byCategory = rows.reduce((a, r) => ({ ...a, [r.category]: Number(a[r.category] || 0) + Number(r.amount) }), {}); return { dateFrom: start, dateTo: end, total: rows.reduce((n, r) => n + Number(r.amount), 0).toFixed(2), count: rows.length, byCategory: Object.entries(byCategory).map(([category, amount]) => ({ category, amount: amount.toFixed(2) })).sort((a,b) => Number(b.amount)-Number(a.amount)) } }
}
